class Employee {
    constructor(id, fullName, age, contact, department) {
        this.id = id; // represents the id generated by the firestore
        this.fullName = fullName;
        this.age = age;
        this.contact = contact;
        this.department = department;
    }
}

export default Employee
